# This is a basic workflow to help you get started with Actions

name: Merge EPG Automatically

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 19 * * *'  # Chạy tự động hàng ngày vào 02:00 (UTC+7)
  workflow_dispatch:  # Cho phép chạy thủ công từ GitHub UI

permissions:
  contents: write  # Cần quyền này để commit và push file

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  merge:
    runs-on: ubuntu-latest  # Máy ảo Linux để chạy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Lấy code từ repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Phiên bản Python (có thể dùng '3.x' cho latest)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Cài đặt thư viện requests

      - name: Run merge script
        run: python epgxml.py  # Chạy script để merge và tạo merged_epg.xml

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add merged_epg.xml
          git commit -m "Auto-update merged EPG" || echo "No changes to commit"
          git push
